# Font Test: English: Hello
#            中文：   你好

[font]
# size = 15
size = 14
# 1234567890
# JetBrains Mono
offset = { x = 0, y = -1 }
[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

# Noto Sans Mono
# [font.bold]
# family = "NotoSansM Nerd Font Mono"
# style = "Bold"
#
# [font.normal]
# family = "NotoSansM Nerd Font Mono"
# style = "Regular"

# Set the meta key to the left alt
[window]
option_as_alt = "OnlyLeft"

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

[general]
import = [
  "~/.config/alacritty/themes/gruvbox_dark_medium.toml"
]
