import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 12.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

# Set the meta key to the left alt
[window]
option_as_alt = "OnlyLeft"

[colors]
draw_bold_text_with_bright_colors = true
