# Font Test: English: Hello
#            中文：   你好

[font]
size = 13.9

# JetBrains Mono
# offset = { x = 1, y = 0 }
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

# Noto Sans Mono
# [font.bold]
# family = "NotoSansM Nerd Font Mono"
# style = "Bold"
#
# [font.normal]
# family = "NotoSansM Nerd Font Mono"
# style = "Regular"

# Set the meta key to the left alt
[window]
option_as_alt = "OnlyLeft"

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

[general]
import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]
